//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4206
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneSync {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationOneSync {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationOneSync() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneSync.LocalizationOneSync", typeof(LocalizationOneSync).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Job.
        /// </summary>
        internal static string btn_addNewJob {
            get {
                return ResourceManager.GetString("btn_addNewJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string btn_preview {
            get {
                return ResourceManager.GetString("btn_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Log.
        /// </summary>
        internal static string btn_showLog {
            get {
                return ResourceManager.GetString("btn_showLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Selected Jobs.
        /// </summary>
        internal static string btn_syncJobs {
            get {
                return ResourceManager.GetString("btn_syncJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only sync jobs assigned to the.
        /// </summary>
        internal static string chb_showPartialSyncJobs {
            get {
                return ResourceManager.GetString("chb_showPartialSyncJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid active Window is needed to update the Taskbar.
        /// </summary>
        internal static string err_activeWindowAndTaskbar {
            get {
                return ResourceManager.GetString("err_activeWindowAndTaskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot copy file {0}.
        /// </summary>
        internal static string err_cannotCopyFile {
            get {
                return ResourceManager.GetString("err_cannotCopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete file {0}.
        /// </summary>
        internal static string err_cannotDeleteFile {
            get {
                return ResourceManager.GetString("err_cannotDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync preview cannot be generated..
        /// </summary>
        internal static string err_cannotPreview {
            get {
                return ResourceManager.GetString("err_cannotPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync preview cannot be generated: {0}.
        /// </summary>
        internal static string err_cannotPreview2 {
            get {
                return ResourceManager.GetString("err_cannotPreview2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot rename file {0}.
        /// </summary>
        internal static string err_cannotRenameFile {
            get {
                return ResourceManager.GetString("err_cannotRenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close the program now? The synchronization is still ongoing..
        /// </summary>
        internal static string err_closeWhileSyncing {
            get {
                return ResourceManager.GetString("err_closeWhileSyncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodbye OneSync.
        /// </summary>
        internal static string err_closeWhileSyncingTitle {
            get {
                return ResourceManager.GetString("err_closeWhileSyncingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database exception: Please check your job name and folder directories for selected jobs.
        /// </summary>
        internal static string err_databaseException {
            get {
                return ResourceManager.GetString("err_databaseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are going to delete job {0}. Continue?.
        /// </summary>
        internal static string err_deleteJob {
            get {
                return ResourceManager.GetString("err_deleteJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete SyncJob.
        /// </summary>
        internal static string err_deleteJobTitle {
            get {
                return ResourceManager.GetString("err_deleteJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are going to delete job {0} but its intermediate storage folder cannot be found. If you continue the deletion, you may corrupt the OneSync core files. Continue?.
        /// </summary>
        internal static string err_deleteJobWithNoIntermediateStorage {
            get {
                return ResourceManager.GetString("err_deleteJobWithNoIntermediateStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete SyncJob -- Intermediate Storage Folder Not Found.
        /// </summary>
        internal static string err_deleteJobWithNoIntermediateStorageTitle {
            get {
                return ResourceManager.GetString("err_deleteJobWithNoIntermediateStorageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory is inaccessible..
        /// </summary>
        internal static string err_directoryInaccessible {
            get {
                return ResourceManager.GetString("err_directoryInaccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid directory path..
        /// </summary>
        internal static string err_directoryInvalid {
            get {
                return ResourceManager.GetString("err_directoryInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not have permission to access directory..
        /// </summary>
        internal static string err_directoryNoPermission {
            get {
                return ResourceManager.GetString("err_directoryNoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory {0} does not exist.
        /// </summary>
        internal static string err_directoryNotExist {
            get {
                return ResourceManager.GetString("err_directoryNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not found: {0}.
        /// </summary>
        internal static string err_directoryNotFound {
            get {
                return ResourceManager.GetString("err_directoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory length cannot exceed 260 characters.
        /// </summary>
        internal static string err_directoryTooLong {
            get {
                return ResourceManager.GetString("err_directoryTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Reported: {0}.
        /// </summary>
        internal static string err_errorReported {
            get {
                return ResourceManager.GetString("err_errorReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(s) cannot be moved to {0}. Please do it manually..
        /// </summary>
        internal static string err_filesCannotBeMoved {
            get {
                return ResourceManager.GetString("err_filesCannotBeMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(s) cannot be moved from old to new intermediary storage. Please do it manually..
        /// </summary>
        internal static string err_filesCannotBeMoved2 {
            get {
                return ResourceManager.GetString("err_filesCannotBeMoved2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The offline help file is not available..
        /// </summary>
        internal static string err_helpFileNotFound {
            get {
                return ResourceManager.GetString("err_helpFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneSync -- Offline Help File Not Found.
        /// </summary>
        internal static string err_helpFileNotFoundTitle {
            get {
                return ResourceManager.GetString("err_helpFileNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient space in {0} to store modified files. Please use a drive with bigger capacity..
        /// </summary>
        internal static string err_insufficientSpace {
            get {
                return ResourceManager.GetString("err_insufficientSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate storage folder cannot be found..
        /// </summary>
        internal static string err_intermediateStorageNotFound {
            get {
                return ResourceManager.GetString("err_intermediateStorageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediary storage path: &quot;{0}&quot; not found..
        /// </summary>
        internal static string err_IntermediateStorageNoutFound {
            get {
                return ResourceManager.GetString("err_IntermediateStorageNoutFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new intermediate storage is too small that it cannot store all the files..
        /// </summary>
        internal static string err_intermediateStorageTooSmall {
            get {
                return ResourceManager.GetString("err_intermediateStorageTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your inputs..
        /// </summary>
        internal static string err_invalidInput {
            get {
                return ResourceManager.GetString("err_invalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync job name cannot be empty.
        /// </summary>
        internal static string err_jobNameCannotEmpty {
            get {
                return ResourceManager.GetString("err_jobNameCannotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncJob name cannot be empty..
        /// </summary>
        internal static string err_jobNameEmpty {
            get {
                return ResourceManager.GetString("err_jobNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync job name cannot exceed 50 characters.
        /// </summary>
        internal static string err_jobNameTooLong {
            get {
                return ResourceManager.GetString("err_jobNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata file is missing or corrupted..
        /// </summary>
        internal static string err_metadataMissing {
            get {
                return ResourceManager.GetString("err_metadataMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata file doesn&apos;t contain source {0}..
        /// </summary>
        internal static string err_metadataMissingSource {
            get {
                return ResourceManager.GetString("err_metadataMissingSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no log for this job currently..
        /// </summary>
        internal static string err_noLogFile {
            get {
                return ResourceManager.GetString("err_noLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one sync job..
        /// </summary>
        internal static string err_noSyncJob {
            get {
                return ResourceManager.GetString("err_noSyncJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 2 number of source folders are allowed to connect to the same intermediate storage folder..
        /// </summary>
        internal static string err_onlyTwoSyncSourceFolders {
            get {
                return ResourceManager.GetString("err_onlyTwoSyncSourceFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path contains illegal characters..
        /// </summary>
        internal static string err_pathIllegal {
            get {
                return ResourceManager.GetString("err_pathIllegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path is too long..
        /// </summary>
        internal static string err_pathTooLong {
            get {
                return ResourceManager.GetString("err_pathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync between folder and its sub-folder is not allowed.
        /// </summary>
        internal static string err_recursive {
            get {
                return ResourceManager.GetString("err_recursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder to be synchronized cannot be in the intermediate storage folder or vice-versa..
        /// </summary>
        internal static string err_recursive2 {
            get {
                return ResourceManager.GetString("err_recursive2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not found.
        /// </summary>
        internal static string err_somethingNotFound {
            get {
                return ResourceManager.GetString("err_somethingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source or Intermediate storage is empty.
        /// </summary>
        internal static string err_sourceIntermediateEmpty {
            get {
                return ResourceManager.GetString("err_sourceIntermediateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source and intermediate path cannot be the same.
        /// </summary>
        internal static string err_sourceSameAsIntermediate {
            get {
                return ResourceManager.GetString("err_sourceSameAsIntermediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder to be synchronized cannot be found..
        /// </summary>
        internal static string err_syncFolderNotFound {
            get {
                return ResourceManager.GetString("err_syncFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder to be synchronized cannot be the same as intermediate storage folder..
        /// </summary>
        internal static string err_syncFolderSameAsIntermediate {
            get {
                return ResourceManager.GetString("err_syncFolderSameAsIntermediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate storage directory is invalid..
        /// </summary>
        internal static string err_syncIntermediateInvalid {
            get {
                return ResourceManager.GetString("err_syncIntermediateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync job {0} is already created.
        /// </summary>
        internal static string err_syncjobCreated {
            get {
                return ResourceManager.GetString("err_syncjobCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected sync job(s) cannot be found..
        /// </summary>
        internal static string err_syncJobNotFound {
            get {
                return ResourceManager.GetString("err_syncJobNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync source directory is invalid..
        /// </summary>
        internal static string err_syncSourceInvalid {
            get {
                return ResourceManager.GetString("err_syncSourceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete sync job at this moment..
        /// </summary>
        internal static string err_unableDeleteJob {
            get {
                return ResourceManager.GetString("err_unableDeleteJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string hdr_action {
            get {
                return ResourceManager.GetString("hdr_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict Resolution.
        /// </summary>
        internal static string hdr_conflictResolution {
            get {
                return ResourceManager.GetString("hdr_conflictResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        internal static string hdr_filePath {
            get {
                return ResourceManager.GetString("hdr_filePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Name.
        /// </summary>
        internal static string hdr_jobName {
            get {
                return ResourceManager.GetString("hdr_jobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original File Path.
        /// </summary>
        internal static string hdr_originalFilePath {
            get {
                return ResourceManager.GetString("hdr_originalFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder.
        /// </summary>
        internal static string hdr_reorder {
            get {
                return ResourceManager.GetString("hdr_reorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string hdr_skip {
            get {
                return ResourceManager.GetString("hdr_skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Source Directory.
        /// </summary>
        internal static string hdr_syncSourceDir {
            get {
                return ResourceManager.GetString("hdr_syncSourceDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Status.
        /// </summary>
        internal static string hdr_syncStatus {
            get {
                return ResourceManager.GetString("hdr_syncStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate Storage Directory.
        /// </summary>
        internal static string hrd_syncIntStorageDir {
            get {
                return ResourceManager.GetString("hrd_syncIntStorageDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying patch.
        /// </summary>
        internal static string lbl_applyingPatch {
            get {
                return ResourceManager.GetString("lbl_applyingPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneSync 3 can only run on computer which has .NET 3.5 SP1 installed..
        /// </summary>
        internal static string lbl_dotNetFrameworkDescriptionText1 {
            get {
                return ResourceManager.GetString("lbl_dotNetFrameworkDescriptionText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please download and then install the suitable version of .NET Framework here:.
        /// </summary>
        internal static string lbl_dotNetFrameworkDescriptionText2 {
            get {
                return ResourceManager.GetString("lbl_dotNetFrameworkDescriptionText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string lbl_download {
            get {
                return ResourceManager.GetString("lbl_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Text:.
        /// </summary>
        internal static string lbl_filterText {
            get {
                return ResourceManager.GetString("lbl_filterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Type:.
        /// </summary>
        internal static string lbl_filterType {
            get {
                return ResourceManager.GetString("lbl_filterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict Files.
        /// </summary>
        internal static string lbl_filterTypeConflictFiles {
            get {
                return ResourceManager.GetString("lbl_filterTypeConflictFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Only.
        /// </summary>
        internal static string lbl_filterTypeCopyOnly {
            get {
                return ResourceManager.GetString("lbl_filterTypeCopyOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Only.
        /// </summary>
        internal static string lbl_filterTypeDeleteOnly {
            get {
                return ResourceManager.GetString("lbl_filterTypeDeleteOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Only.
        /// </summary>
        internal static string lbl_filterTypeRenameOnly {
            get {
                return ResourceManager.GetString("lbl_filterTypeRenameOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        internal static string lbl_filterTypeShowAll {
            get {
                return ResourceManager.GetString("lbl_filterTypeShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating patch.
        /// </summary>
        internal static string lbl_generatingPatch {
            get {
                return ResourceManager.GetString("lbl_generatingPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing to sync.
        /// </summary>
        internal static string lbl_peparingToSync {
            get {
                return ResourceManager.GetString("lbl_peparingToSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Preview.
        /// </summary>
        internal static string lbl_preview {
            get {
                return ResourceManager.GetString("lbl_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string lbl_previewDone {
            get {
                return ResourceManager.GetString("lbl_previewDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of sync jobs:
        ///
        ///Current syncing job:.
        /// </summary>
        internal static string lbl_syncDescription {
            get {
                return ResourceManager.GetString("lbl_syncDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermidiate Storage Location:.
        /// </summary>
        internal static string lbl_syncIntStorageDir {
            get {
                return ResourceManager.GetString("lbl_syncIntStorageDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Job Name:.
        /// </summary>
        internal static string lbl_syncJobName {
            get {
                return ResourceManager.GetString("lbl_syncJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder to Sync:.
        /// </summary>
        internal static string lbl_syncSourceDir {
            get {
                return ResourceManager.GetString("lbl_syncSourceDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder to Sync.
        /// </summary>
        internal static string lbl_syncSourceDir2 {
            get {
                return ResourceManager.GetString("lbl_syncSourceDir2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From intermediate storage.
        /// </summary>
        internal static string log_fromIntermediateStorage {
            get {
                return ResourceManager.GetString("log_fromIntermediateStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To intermediate storage.
        /// </summary>
        internal static string log_toIntermediateStorage {
            get {
                return ResourceManager.GetString("log_toIntermediateStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to onesynclog.xsl.
        /// </summary>
        internal static string log_xslFileName {
            get {
                return ResourceManager.GetString("log_xslFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new version of OneSync available. Do you want to download it now?.
        /// </summary>
        internal static string msg_newOneSyncVersion {
            get {
                return ResourceManager.GetString("msg_newOneSyncVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version Of OneSync Available.
        /// </summary>
        internal static string msg_newOneSyncVersionTitle {
            get {
                return ResourceManager.GetString("msg_newOneSyncVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneSync is already running. There should be only one instance of OneSync all the time..
        /// </summary>
        internal static string msg_oneInstance {
            get {
                return ResourceManager.GetString("msg_oneInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneSync -- One Instance Only.
        /// </summary>
        internal static string msg_oneInstanceTitle {
            get {
                return ResourceManager.GetString("msg_oneInstanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing through Dropbox now.
        /// </summary>
        internal static string msg_progressBar1 {
            get {
                return ResourceManager.GetString("msg_progressBar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing through Dropbox is done.
        /// </summary>
        internal static string msg_progressBar2 {
            get {
                return ResourceManager.GetString("msg_progressBar2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing through Dropbox is done but with error.
        /// </summary>
        internal static string msg_progressBar3 {
            get {
                return ResourceManager.GetString("msg_progressBar3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization completed..
        /// </summary>
        internal static string msg_syncCompleted {
            get {
                return ResourceManager.GetString("msg_syncCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing....
        /// </summary>
        internal static string msg_syncing {
            get {
                return ResourceManager.GetString("msg_syncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing: {0}.
        /// </summary>
        internal static string msg_syncingDirectory {
            get {
                return ResourceManager.GetString("msg_syncingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync job completed.
        /// </summary>
        internal static string msg_syncJobCompleted {
            get {
                return ResourceManager.GetString("msg_syncJobCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization completed..
        /// </summary>
        internal static string msg_updatedDropBox {
            get {
                return ResourceManager.GetString("msg_updatedDropBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files are synced but they are still being uploaded to the Dropbox server..
        /// </summary>
        internal static string msg_updatingDropBox {
            get {
                return ResourceManager.GetString("msg_updatingDropBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string not_exitName {
            get {
                return ResourceManager.GetString("not_exitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help (User Manual).
        /// </summary>
        internal static string not_helpName {
            get {
                return ResourceManager.GetString("not_helpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click the icon to show the program window..
        /// </summary>
        internal static string not_message1 {
            get {
                return ResourceManager.GetString("not_message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneSync is still running.
        /// </summary>
        internal static string not_messageTitle1 {
            get {
                return ResourceManager.GetString("not_messageTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneSync.
        /// </summary>
        internal static string not_name {
            get {
                return ResourceManager.GetString("not_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open OneSync 3.
        /// </summary>
        internal static string not_openName {
            get {
                return ResourceManager.GetString("not_openName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to browse folders.
        /// </summary>
        internal static string tot_browseFolder {
            get {
                return ResourceManager.GetString("tot_browseFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Subsequent Jobs.
        /// </summary>
        internal static string tot_cancelJobs {
            get {
                return ResourceManager.GetString("tot_cancelJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this job.
        /// </summary>
        internal static string tot_deleteJob {
            get {
                return ResourceManager.GetString("tot_deleteJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit this job.
        /// </summary>
        internal static string tot_editJob {
            get {
                return ResourceManager.GetString("tot_editJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string tot_helpFile {
            get {
                return ResourceManager.GetString("tot_helpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview selected job.
        /// </summary>
        internal static string tot_previewJob {
            get {
                return ResourceManager.GetString("tot_previewJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show selected job&apos;s log.
        /// </summary>
        internal static string tot_showLog {
            get {
                return ResourceManager.GetString("tot_showLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneSync System Requirement.
        /// </summary>
        internal static string win_dotNetFrameworkRequirement {
            get {
                return ResourceManager.GetString("win_dotNetFrameworkRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneSync - Sync Preview.
        /// </summary>
        internal static string win_syncPreviewWindow {
            get {
                return ResourceManager.GetString("win_syncPreviewWindow", resourceCulture);
            }
        }
    }
}
