//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4206
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneSync {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationOneSyncChinese {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationOneSyncChinese() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneSync.LocalizationOneSyncChinese", typeof(LocalizationOneSyncChinese).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新的同步工作.
        /// </summary>
        internal static string btn_addNewJob {
            get {
                return ResourceManager.GetString("btn_addNewJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预览工作.
        /// </summary>
        internal static string btn_preview {
            get {
                return ResourceManager.GetString("btn_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示记录.
        /// </summary>
        internal static string btn_showLog {
            get {
                return ResourceManager.GetString("btn_showLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步所选择的工作.
        /// </summary>
        internal static string btn_syncJobs {
            get {
                return ResourceManager.GetString("btn_syncJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只显示部分同步工作，根据所选择的.
        /// </summary>
        internal static string chb_showPartialSyncJobs {
            get {
                return ResourceManager.GetString("chb_showPartialSyncJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 为了更新任务栏，再此需要一个有效使用的视窗.
        /// </summary>
        internal static string err_activeWindowAndTaskbar {
            get {
                return ResourceManager.GetString("err_activeWindowAndTaskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不能拷贝此档案 {0}.
        /// </summary>
        internal static string err_cannotCopyFile {
            get {
                return ResourceManager.GetString("err_cannotCopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不能删除此档案 {0}.
        /// </summary>
        internal static string err_cannotDeleteFile {
            get {
                return ResourceManager.GetString("err_cannotDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法预览同步工作。.
        /// </summary>
        internal static string err_cannotPreview {
            get {
                return ResourceManager.GetString("err_cannotPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法预览同步工作：{0}.
        /// </summary>
        internal static string err_cannotPreview2 {
            get {
                return ResourceManager.GetString("err_cannotPreview2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不能修改档案名 {0}.
        /// </summary>
        internal static string err_cannotRenameFile {
            get {
                return ResourceManager.GetString("err_cannotRenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步工作还在进行当中，确定要关闭OneSync吗？.
        /// </summary>
        internal static string err_closeWhileSyncing {
            get {
                return ResourceManager.GetString("err_closeWhileSyncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭OneSync.
        /// </summary>
        internal static string err_closeWhileSyncingTitle {
            get {
                return ResourceManager.GetString("err_closeWhileSyncingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据库例外：请检查同步工作名是否合格以及所牵涉到的文件夹目录是否存在.
        /// </summary>
        internal static string err_databaseException {
            get {
                return ResourceManager.GetString("err_databaseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定删除此同步工作： {0}？.
        /// </summary>
        internal static string err_deleteJob {
            get {
                return ResourceManager.GetString("err_deleteJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除同步工作.
        /// </summary>
        internal static string err_deleteJobTitle {
            get {
                return ResourceManager.GetString("err_deleteJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你将要删除的同步工作： {0} 的中间储藏地址不存在。 如果将此工作删除，OneSync的主要文件可能受到影响。 确定继续？.
        /// </summary>
        internal static string err_deleteJobWithNoIntermediateStorage {
            get {
                return ResourceManager.GetString("err_deleteJobWithNoIntermediateStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除同步工作 -- 中间储藏地址不存在.
        /// </summary>
        internal static string err_deleteJobWithNoIntermediateStorageTitle {
            get {
                return ResourceManager.GetString("err_deleteJobWithNoIntermediateStorageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法登入档案目录。.
        /// </summary>
        internal static string err_directoryInaccessible {
            get {
                return ResourceManager.GetString("err_directoryInaccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 档案目录不合格.
        /// </summary>
        internal static string err_directoryInvalid {
            get {
                return ResourceManager.GetString("err_directoryInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法登入档案目录.
        /// </summary>
        internal static string err_directoryNoPermission {
            get {
                return ResourceManager.GetString("err_directoryNoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 不存在.
        /// </summary>
        internal static string err_directoryNotExist {
            get {
                return ResourceManager.GetString("err_directoryNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 档案目录不存在： {0}.
        /// </summary>
        internal static string err_directoryNotFound {
            get {
                return ResourceManager.GetString("err_directoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步档案目录不可超过260个英文字母.
        /// </summary>
        internal static string err_directoryTooLong {
            get {
                return ResourceManager.GetString("err_directoryTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统发生错误： {0}.
        /// </summary>
        internal static string err_errorReported {
            get {
                return ResourceManager.GetString("err_errorReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 档案不能被移动至 {0}。请自行移动档案。.
        /// </summary>
        internal static string err_filesCannotBeMoved {
            get {
                return ResourceManager.GetString("err_filesCannotBeMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 档案不能从旧的中间储藏地址移至新的中间储藏地址。请自行移动档案。.
        /// </summary>
        internal static string err_filesCannotBeMoved2 {
            get {
                return ResourceManager.GetString("err_filesCannotBeMoved2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户手册不存在。.
        /// </summary>
        internal static string err_helpFileNotFound {
            get {
                return ResourceManager.GetString("err_helpFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneSync -- 用户手册不存在.
        /// </summary>
        internal static string err_helpFileNotFoundTitle {
            get {
                return ResourceManager.GetString("err_helpFileNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 储存空间不足。请使用足够空间的储存地。.
        /// </summary>
        internal static string err_insufficientSpace {
            get {
                return ResourceManager.GetString("err_insufficientSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法寻获中间储藏档案.
        /// </summary>
        internal static string err_intermediateStorageNotFound {
            get {
                return ResourceManager.GetString("err_intermediateStorageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法寻获此中间储藏地址：“{0}”。.
        /// </summary>
        internal static string err_IntermediateStorageNoutFound {
            get {
                return ResourceManager.GetString("err_IntermediateStorageNoutFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新的中间储藏地址储存空间过小，因此有些档案无法存入新的中间储藏地址。.
        /// </summary>
        internal static string err_intermediateStorageTooSmall {
            get {
                return ResourceManager.GetString("err_intermediateStorageTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请检查输入值。.
        /// </summary>
        internal static string err_invalidInput {
            get {
                return ResourceManager.GetString("err_invalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步工作名不可置空.
        /// </summary>
        internal static string err_jobNameCannotEmpty {
            get {
                return ResourceManager.GetString("err_jobNameCannotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步工作名不可置空.
        /// </summary>
        internal static string err_jobNameEmpty {
            get {
                return ResourceManager.GetString("err_jobNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步工作名不可超过25个中文单字.
        /// </summary>
        internal static string err_jobNameTooLong {
            get {
                return ResourceManager.GetString("err_jobNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 元数据不存在或已被破坏。.
        /// </summary>
        internal static string err_metadataMissing {
            get {
                return ResourceManager.GetString("err_metadataMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 元数据不存有此原址 {0}..
        /// </summary>
        internal static string err_metadataMissingSource {
            get {
                return ResourceManager.GetString("err_metadataMissingSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此同步工作还未有任何的记录。.
        /// </summary>
        internal static string err_noLogFile {
            get {
                return ResourceManager.GetString("err_noLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择至少一个同步工作。.
        /// </summary>
        internal static string err_noSyncJob {
            get {
                return ResourceManager.GetString("err_noSyncJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每个中间储藏地址只可以使用于最多两个同步工作.
        /// </summary>
        internal static string err_onlyTwoSyncSourceFolders {
            get {
                return ResourceManager.GetString("err_onlyTwoSyncSourceFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 档案目录不合格.
        /// </summary>
        internal static string err_pathIllegal {
            get {
                return ResourceManager.GetString("err_pathIllegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 档案目录过长.
        /// </summary>
        internal static string err_pathTooLong {
            get {
                return ResourceManager.GetString("err_pathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件夹及其子文件夹间的同步不被允许.
        /// </summary>
        internal static string err_recursive {
            get {
                return ResourceManager.GetString("err_recursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步源档案不可存在于或者与中间储藏档案相同，反之亦然.
        /// </summary>
        internal static string err_recursive2 {
            get {
                return ResourceManager.GetString("err_recursive2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 不存在.
        /// </summary>
        internal static string err_somethingNotFound {
            get {
                return ResourceManager.GetString("err_somethingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步文件与中间储藏地址不可置空.
        /// </summary>
        internal static string err_sourceIntermediateEmpty {
            get {
                return ResourceManager.GetString("err_sourceIntermediateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步文件不可与中间储藏地址相同.
        /// </summary>
        internal static string err_sourceSameAsIntermediate {
            get {
                return ResourceManager.GetString("err_sourceSameAsIntermediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法寻获同步源档案.
        /// </summary>
        internal static string err_syncFolderNotFound {
            get {
                return ResourceManager.GetString("err_syncFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步源档案不可与中间储藏档案相同.
        /// </summary>
        internal static string err_syncFolderSameAsIntermediate {
            get {
                return ResourceManager.GetString("err_syncFolderSameAsIntermediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中间储藏地址不合格.
        /// </summary>
        internal static string err_syncIntermediateInvalid {
            get {
                return ResourceManager.GetString("err_syncIntermediateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此同步工作：{0}已存在.
        /// </summary>
        internal static string err_syncjobCreated {
            get {
                return ResourceManager.GetString("err_syncjobCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所选的同步工作不存在。.
        /// </summary>
        internal static string err_syncJobNotFound {
            get {
                return ResourceManager.GetString("err_syncJobNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步源档案目录不合格.
        /// </summary>
        internal static string err_syncSourceInvalid {
            get {
                return ResourceManager.GetString("err_syncSourceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法删除此同步工作。.
        /// </summary>
        internal static string err_unableDeleteJob {
            get {
                return ResourceManager.GetString("err_unableDeleteJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动作.
        /// </summary>
        internal static string hdr_action {
            get {
                return ResourceManager.GetString("hdr_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步冲突解决方法.
        /// </summary>
        internal static string hdr_conflictResolution {
            get {
                return ResourceManager.GetString("hdr_conflictResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件路径.
        /// </summary>
        internal static string hdr_filePath {
            get {
                return ResourceManager.GetString("hdr_filePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步工作名.
        /// </summary>
        internal static string hdr_jobName {
            get {
                return ResourceManager.GetString("hdr_jobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始文件路径.
        /// </summary>
        internal static string hdr_originalFilePath {
            get {
                return ResourceManager.GetString("hdr_originalFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排序.
        /// </summary>
        internal static string hdr_reorder {
            get {
                return ResourceManager.GetString("hdr_reorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 省略.
        /// </summary>
        internal static string hdr_skip {
            get {
                return ResourceManager.GetString("hdr_skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步文件.
        /// </summary>
        internal static string hdr_syncSourceDir {
            get {
                return ResourceManager.GetString("hdr_syncSourceDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步状态.
        /// </summary>
        internal static string hdr_syncStatus {
            get {
                return ResourceManager.GetString("hdr_syncStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中间储藏地址.
        /// </summary>
        internal static string hrd_syncIntStorageDir {
            get {
                return ResourceManager.GetString("hrd_syncIntStorageDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneSync 3 只能在安装有 .NET 3.5 SP1 的系统上顺利运行。.
        /// </summary>
        internal static string lbl_dotNetFrameworkDescriptionText1 {
            get {
                return ResourceManager.GetString("lbl_dotNetFrameworkDescriptionText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请到以下网站下载及安装恰当的 .NET 版本：.
        /// </summary>
        internal static string lbl_dotNetFrameworkDescriptionText2 {
            get {
                return ResourceManager.GetString("lbl_dotNetFrameworkDescriptionText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载：.
        /// </summary>
        internal static string lbl_download {
            get {
                return ResourceManager.GetString("lbl_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关键字：.
        /// </summary>
        internal static string lbl_filterText {
            get {
                return ResourceManager.GetString("lbl_filterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预览种类：.
        /// </summary>
        internal static string lbl_filterType {
            get {
                return ResourceManager.GetString("lbl_filterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存在冲突的文件.
        /// </summary>
        internal static string lbl_filterTypeConflictFiles {
            get {
                return ResourceManager.GetString("lbl_filterTypeConflictFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将被拷贝的文件.
        /// </summary>
        internal static string lbl_filterTypeCopyOnly {
            get {
                return ResourceManager.GetString("lbl_filterTypeCopyOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将被删除的文件.
        /// </summary>
        internal static string lbl_filterTypeDeleteOnly {
            get {
                return ResourceManager.GetString("lbl_filterTypeDeleteOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将被易名的文件.
        /// </summary>
        internal static string lbl_filterTypeRenameOnly {
            get {
                return ResourceManager.GetString("lbl_filterTypeRenameOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部的文件.
        /// </summary>
        internal static string lbl_filterTypeShowAll {
            get {
                return ResourceManager.GetString("lbl_filterTypeShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步预览.
        /// </summary>
        internal static string lbl_preview {
            get {
                return ResourceManager.GetString("lbl_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束预览.
        /// </summary>
        internal static string lbl_previewDone {
            get {
                return ResourceManager.GetString("lbl_previewDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步工作量:
        ///
        ///进行中的工作:.
        /// </summary>
        internal static string lbl_syncDescription {
            get {
                return ResourceManager.GetString("lbl_syncDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中间储藏地址:.
        /// </summary>
        internal static string lbl_syncIntStorageDir {
            get {
                return ResourceManager.GetString("lbl_syncIntStorageDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步工作名:.
        /// </summary>
        internal static string lbl_syncJobName {
            get {
                return ResourceManager.GetString("lbl_syncJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步文件:.
        /// </summary>
        internal static string lbl_syncSourceDir {
            get {
                return ResourceManager.GetString("lbl_syncSourceDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步文件.
        /// </summary>
        internal static string lbl_syncSourceDir2 {
            get {
                return ResourceManager.GetString("lbl_syncSourceDir2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取自中间储藏地址.
        /// </summary>
        internal static string log_fromIntermediateStorage {
            get {
                return ResourceManager.GetString("log_fromIntermediateStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 传送至中间储藏地址.
        /// </summary>
        internal static string log_toIntermediateStorage {
            get {
                return ResourceManager.GetString("log_toIntermediateStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to onesynclog(Chinese).xsl.
        /// </summary>
        internal static string log_xslFileName {
            get {
                return ResourceManager.GetString("log_xslFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步顺利完成。.
        /// </summary>
        internal static string msg_syncCompleted {
            get {
                return ResourceManager.GetString("msg_syncCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步中.......
        /// </summary>
        internal static string msg_syncing {
            get {
                return ResourceManager.GetString("msg_syncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步中: {0}.
        /// </summary>
        internal static string msg_syncingDirectory {
            get {
                return ResourceManager.GetString("msg_syncingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步工作完成。.
        /// </summary>
        internal static string msg_syncJobCompleted {
            get {
                return ResourceManager.GetString("msg_syncJobCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        internal static string not_exitName {
            get {
                return ResourceManager.GetString("not_exitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助（英文版用户手册）.
        /// </summary>
        internal static string not_helpName {
            get {
                return ResourceManager.GetString("not_helpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 双击此图标以显示OneSync视窗。.
        /// </summary>
        internal static string not_message1 {
            get {
                return ResourceManager.GetString("not_message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneSync 仍在运行中.
        /// </summary>
        internal static string not_messageTitle1 {
            get {
                return ResourceManager.GetString("not_messageTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneSync.
        /// </summary>
        internal static string not_name {
            get {
                return ResourceManager.GetString("not_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开启 OneSync 3.
        /// </summary>
        internal static string not_openName {
            get {
                return ResourceManager.GetString("not_openName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点击浏览文件夹.
        /// </summary>
        internal static string tot_browseFolder {
            get {
                return ResourceManager.GetString("tot_browseFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止随后同步工作.
        /// </summary>
        internal static string tot_cancelJobs {
            get {
                return ResourceManager.GetString("tot_cancelJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除此工作.
        /// </summary>
        internal static string tot_deleteJob {
            get {
                return ResourceManager.GetString("tot_deleteJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑此工作.
        /// </summary>
        internal static string tot_editJob {
            get {
                return ResourceManager.GetString("tot_editJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助.
        /// </summary>
        internal static string tot_helpFile {
            get {
                return ResourceManager.GetString("tot_helpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预览同步工作.
        /// </summary>
        internal static string tot_previewJob {
            get {
                return ResourceManager.GetString("tot_previewJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示同步记录.
        /// </summary>
        internal static string tot_showLog {
            get {
                return ResourceManager.GetString("tot_showLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneSync 系统需求.
        /// </summary>
        internal static string win_dotNetFrameworkRequirement {
            get {
                return ResourceManager.GetString("win_dotNetFrameworkRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneSync - 同步预览.
        /// </summary>
        internal static string win_syncPreviewWindow {
            get {
                return ResourceManager.GetString("win_syncPreviewWindow", resourceCulture);
            }
        }
    }
}
